name: prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SSH_KEY_FILE_NAME: tiomhs.pem
  APP_DIR: recipes-vue

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Extract the environment variable
        # run: echo "${{ secrets.STAGING_ENV_VARS }}" > .env
      - name: Install dependencies
        run: npm install 
      - name: Build
        run: npm run build
      - name: Store SSH key
        run: echo "${{ secrets.SSH_KEY_CONTENT }}" > ${{ env.SSH_KEY_FILE_NAME }}
      - name: Change SSH key permission
        run: chmod 444 ${{ env.SSH_KEY_FILE_NAME }} # fix for scp-action@v0.1.7 and ssh-action@v1.0.3
      - name: Copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key_path: ${{ env.SSH_KEY_FILE_NAME }}
          source: './dist,./node_modules,ecosystem.staging.config.cjs,package.json'
          target: '/home/${{ secrets.SSH_USERNAME }}/${{ env.APP_DIR }}'
      - name: Executing remote command using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key_path: ${{ env.SSH_KEY_FILE_NAME }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            source ~/.profile
            cd /home/${{ secrets.SSH_USERNAME }}/${{ env.APP_DIR }}
            pm2 reload ecosystem.staging.config.cjs
            pm2 save